#pragma once

#define DEFAULT_BLINK_BRIGHTNESS 0.7
#define DEFAULT_DISPLAY_SECONDS true
#define DEFAULT_NIGHT_TIME_ENABLED true
#define DEFAULT_LIGHT_INFLUENCE 50
#define DEFAULT_NIGHT_TIME_BEGIN 2300
#define DEFAULT_NIGHT_TIME_END 600
#define DEFAULT_BRIGHTNESS 10
#define DEFAULT_DIMM_SECONDS false